In [4]:
import pandas as pd
df = pd.read_csv("crop_yield.csv")
df

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare
0,West,Sandy,Cotton,897.077239,27.676966,False,True,Cloudy,122,6.555816
1,South,Clay,Rice,992.673282,18.026142,True,True,Rainy,140,8.527341
2,North,Loam,Barley,147.998025,29.794042,False,False,Sunny,106,1.127443
3,North,Sandy,Soybean,986.866331,16.644190,False,True,Rainy,146,6.517573
4,South,Silt,Wheat,730.379174,31.620687,True,True,Cloudy,110,7.248251
...,...,...,...,...,...,...,...,...,...,...
999995,West,Silt,Rice,302.805345,27.987428,False,False,Sunny,76,1.347586
999996,South,Chalky,Barley,932.991383,39.661039,True,False,Rainy,93,7.311594
999997,North,Peaty,Cotton,867.362046,24.370042,True,False,Cloudy,108,5.763182
999998,West,Silt,Wheat,492.812857,33.045505,False,False,Sunny,102,2.070159
999999,West,Sandy,Maize,180.936180,27.298847,True,False,Sunny,76,2.937243

In [5]:
df.head()

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare
0,West,Sandy,Cotton,897.077239,27.676966,False,True,Cloudy,122,6.555816
1,South,Clay,Rice,992.673282,18.026142,True,True,Rainy,140,8.527341
2,North,Loam,Barley,147.998025,29.794042,False,False,Sunny,106,1.127443
3,North,Sandy,Soybean,986.866331,16.644190,False,True,Rainy,146,6.517573
4,South,Silt,Wheat,730.379174,31.620687,True,True,Cloudy,110,7.248251

In [6]:
#slicing the dataset
x=df.iloc[:,0:1].values
y=df.iloc[:,-1].values
print(x)
print(y)

[['West']
 ['South']
 ['North']
 ...
 ['North']
 ['West']
 ['West']]
[6.55581626 8.52734091 1.12744334 ... 5.76318192 2.07015871 2.93724319]

In [7]:
#splitting the dataset into training set and testing set 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=1/3,random_state=0)

In [8]:
print(df.shape)

(1000000, 10)

In [9]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(666666, 1)
(333334, 1)
(666666,)
(333334,)

In [ ]:
#calculate the mean values of input and output
import numpy as np
x_mean = np.mean(x_train)
y_mean = np.mean(y_train)
print(x_mean,y_mean)

In [ ]:
#calculate intercept and coefficient
n = len(x_train)
num,den = 0,0
for i in range(n):
    num+=(x_train[i]-x_mean)*(y_train[i]-y_mean)
    den+=(x_train[i]-x_mean)**2

b1 = num/den
b0 = y_mean - (b1*x_mean)
print("b0:",b0)
print("b1:",b1)

In [ ]:
#predicting results on test dataset
y_pred_code = b0+b1*x_test
print(y_pred_code)

In [ ]:
print(y_test)
print("\n ",x_test)

In [ ]:
#mean square error
n1 = len(y_test)
mse = 0
for i in range(n1):
    mse+=(y_test[i]-y_pred_code[i])**2

mse = mse/n1
print(mse)

#root mean square error
rmse = np.sqrt(mse)S
print(rmse)

In [ ]:
#create an object of the algorithm /model
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [ ]:
#train the model
reg.fit(x_train,y_train)

In [ ]:
#predict the model on testing dataset
y_pred = reg.predict(x_test)
print(y_pred)

In [ ]:
#calculate the intercept and the coefficient
print("intercept",reg.intercept_)
print("coefficient",reg.coef_)

In [ ]:
#evaluation metrics
from sklearn import metrics
print("mean absolute error:")
print(metrics.mean_absolute_error(y_test,y_pred))

In [ ]:
#evaluation metrics
from sklearn import metrics
print("mean absolute error:",metrics.mean_absolute_error(y_test,y_pred))
print("mean squared error:",metrics.mean_squared_error(y_test,y_pred))
print("root mean squared error:", np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

In [ ]:
#visualization
import matplotlib.pyplot as plt
plt.scatter(x_train,y_train,color="red")
plt.plot(x_train,reg.predict(x_train),color="blue")
plt.title("salary vs experience - training set")
plt.xlabel("years of experience")
plt.ylabel("salary")
plt.show()

In [ ]:
#visualization
plt.scatter(x_test,y_pred,color="red")
plt.plot(x_train,reg.predict(x_train),color="blue")
plt.title("salary vs experience - test set and predicted values")
plt.xlabel("years of experience")
plt.ylabel("salary")
plt.show()

In [ ]:
#visualization
plt.scatter(x_test,y_test,color="red")
plt.plot(x_train,reg.predict(x_train),color="blue")
plt.title("salary vs experience - testset and actual values of y_test")
plt.xlabel("years of experience")
plt.ylabel("salary")
plt.show()